testcpp_libs = $(top_builddir)/src/orb/libORBit-2.la \
               $(top_builddir)/src/orb-cpp/liborbitcpp.la \
$(ORBIT_LIBS)

INCLUDES =                                 \
	-I$(top_srcdir)/include            \
	-I$(top_builddir)/include          \
	-I$(top_builddir)/src              \
	-I$(top_builddir)/src/ORBitutil    \
	-I$(top_srcdir)/src/orb            \
	-I$(top_srcdir)/src                \
	-DORBIT2_INTERNAL_API              \
	$(ORBIT_CFLAGS) \
  -Igenerated \
  -D_ORBITCPP_TESTCODE

idl_file = $(idlname).idl

EXTRA_DIST = $(idl_file)
