#include "config.h"

#include "orbit-idl-c-backend.h"
#include <string.h>

static void
cc_small_build_interfaces (OIDL_C_Info *ci,
			   IDL_tree     tree)
{
	if (!tree)
		return;

	switch (IDL_NODE_TYPE (tree)) {
	case IDLN_MODULE:
		cc_small_build_interfaces (
			ci, IDL_MODULE (tree).definition_list);
		break;
	case IDLN_LIST: {
		IDL_tree sub;
		for (sub = tree; sub; sub = IDL_LIST (sub).next)
			cc_small_build_interfaces (
				ci, IDL_LIST (sub).data);
		break;
	}
	case IDLN_INTERFACE: {
		char *id;

		id = IDL_ns_ident_to_qstring (IDL_IDENT_TO_NS (
			IDL_INTERFACE (tree).ident), "_", 0);

		fprintf (ci->fh, "\t&%s__itype,\n", id);

		g_free (id);

		cc_small_build_interfaces (
			ci, IDL_INTERFACE(tree).body);
		break;
	}
	default:
		break;
	}
}

void
orbit_idl_output_c_imodule (OIDL_Output_Tree *tree,
			    OIDL_Run_Info    *rinfo,
			    OIDL_C_Info      *ci)
{
	fprintf (ci->fh, "/*\n"
		 " * This file was generated by orbit-idl - DO NOT EDIT!\n"
		 " */\n\n");
	fprintf (ci->fh, "#include <string.h>\n");
	fprintf (ci->fh, "#define ORBIT_IDL_C_IMODULE\n");
	fprintf (ci->fh, "#define %s_IMODLE\n\n", ci->c_base_name);

	fprintf (ci->fh, "#include \"%s-common.c\"\n\n", ci->base_name);

	fprintf (ci->fh, "#include <orbit/orb-core/orbit-small.h>\n\n");

	fprintf (ci->fh, "static ORBit_IInterface *%s__iinterfaces[] = {\n",
		 ci->base_name);

	cc_small_build_interfaces (ci, tree->tree);

	fprintf (ci->fh, "\tNULL\n};\n");

	fprintf (ci->fh, "ORBit_IModule orbit_imodule_data = {\n");
	fprintf (ci->fh, "   %d,\n", ORBIT_CONFIG_SERIAL);
	fprintf (ci->fh, "   %s__iinterfaces\n", ci->base_name);
	fprintf (ci->fh, "};\n\n");
}

